name: 'Google Terraform Destroy'
on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Destroy Google Infrastructure'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: 'Authenticate with service account'
      run: echo $GCS_SA >> "key.json" && gcloud auth activate-service-account --key-file key.json
      env:
        GCS_SA: ${{ secrets.GOOGLE_STORAGE_SA }}

    - name: 'Google State Copy'
      run: gsutil cp gs://jsa-tf-state/default.tfstate terraform.tfstate

    - name: 'Init Backend'
      run: terraform init

    - name: 'Debug'
      uses: actions/checkout@v2
      run: ls

    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}use given 