name: 'Terraform Destroy'
on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: 'Google State Copy'
      run: gsutil cp gs://jsa-tf-state/default.tfstate .
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Destroy
      run: terraform destroy
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}