name: 'Terraform CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      working-directory: ./playground/gcp

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      working-directory: ./playground/gcp

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./playground/gcp

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      working-directory: ./playground/gcp

    - name: Terraform Apply
      if : github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply - auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      working-directory: ./playground/gcp