name: 'Terraform Destroy'
on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Destroy Google Infrastructure'
    runs-on: ubuntu-latest

    defaults:
      run: echo ${{ GOOGLE_STORAGE_SA }}
        shell: bash
    
    steps:
    - name: 'Authenticate with service account'
      run: gcloud auth list

    - name: 'Google State Copy'
      run: gsutil cp gs://jsa-tf-state/default.tfstate .