name: 'Terraform Destroy'
on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Destroy Google Infrastructure'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    - name: 'Authenticate with service account'
      run: echo $GCS_SA
      env:
        GCS_SA: ${{ secrets.GOOGLE_STORAGE_SA }}

    - name: 'Google State Copy'
      run: gsutil cp gs://jsa-tf-state/default.tfstate .